# Generated by Django 4.0.5 on 2022-06-22 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_py', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_uploaded', to='App.user')),
                ('user_who_like', models.ManyToManyField(related_name='liked_books', to='App.user')),
            ],
        ),
    ]
