# Generated by Django 4.0.5 on 2022-06-22 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_bookmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookManager',
        ),
    ]
