# Generated by Django 4.0.5 on 2022-06-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TVShow_App', '0002_showmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowManager',
        ),
    ]
